### ISSUE TITLE
Lakka has "no signal" on XU4

### ISSUE THREAD

**Issue by AndTheCookies** [libretro/Lakka#307]
I have [this image](http://www.lakka.tv/get/windows/odroidxu3/) burned to an eMMC card. The card was previously used with an ODROID U3, but I used [the eMMC Repair Tool](http://forum.odroid.com/viewtopic.php?f=53&t=969) to ensure compatibility with the XU4.

The ODROID powers up, but there is no signal on the screen. I have tried a 1080p Panasonic television and a 720p LCD monitor. Every possible _sentenv_ setting in **boot.ini** has been tested. Nothing works.

**Comment by cudencuden** [comment]
have u tested with microSD as your boot device? works fine for me this way..never used eMMC card with my xu4 before.

**Comment by AndTheCookies** [comment]
Yes. I have tried microSD. No luck. :(

**Comment by Kivutar** [comment]
The SSH service is started already. You don't need to start it.

**Comment by AndTheCookies** [comment]
I have used Putty in Windows 10 to SSH into other XU4 images, but I do not know how to SSH into Lakka.

Assuming I was able to do it, what would I be looking for?

**Comment by Kivutar** [comment]
User: root
Pass: root
Host: lakka

And it should work

**Comment by AndTheCookies** [comment]
Thanks, guys. Are there commands I could feed through SSH to try different resolutions / display settings?

**Comment by cudencuden** [comment]
in ssh you can systemctl stop retroarch then in Windows browse to \\lakka then find n edit config file. then do systemctl start retroarch

**Comment by Kivutar** [comment]
@AndTheCookies not really, the only things managing the real resolution are either in the boot.ini, either backed in the kernel.

Are you sure of what this eMMC repair tool does? There is no need to change anything on the XU3 image to make it compatible with XU4 (at least for lakka).

**Comment by AndTheCookies** [comment]
I was instructed to use the eMMC repair tool because the XU4 was not
turning on. I had to do this because the eMMC was previously used with an
ODROID U3.

Also, the switch on the XU4 is set to boot from the eMMC. The XU4 works
with other images just fine. Lakka is the only image that does not want to
output a video signal ...

> @AndTheCookies <https://github.com/AndTheCookies> not really, the only
> things managing the real resolution are either in the boot.ini, either
> backed in the kernel.
>
> Are you sure of what this eMMC repair tool does? There is no need to
> change anything on the XU3 image to make it compatible with XU4 (at least
> for lakka).
>
>

**Comment by Kivutar** [comment]
I will upgrade our XU3 kernel and platform init then.

**Comment by Kivutar** [comment]
The XU3 kernel is up to date. Can you just try reflashing, without using the repair tool, and try the image on more than one TV please?

**Comment by AndTheCookies** [comment]
Kivutar, thank you. I will try downloading the up-to-date XU3 kernel and reflashing the eMMC.

That being said, I have tried multiple televisions to no avail in the past.

**Comment by AndTheCookies** [comment]
- Redownloaded the image
- Reflashed the eMMC card
- No signal

That being said, I was able to SSH into Lakka. I am logged in as root. Anything I can do to troubleshoot this from here?

**Comment by Kivutar** [comment]
Sorry but I run out of ideas for now. I checked again the XU3 nightly build, it's working fine on the two TVs I have :(

**Comment by Rodrigomezs** [comment]
I have the same problem with my XU4, no signal in some TVs, in other TVs works with same HDMI wire. I fixed the problem in Odroid TurboStation imagee using this sentence in boot.ini:
`setenv videoconfig "drm_kms_helper.edid_firmware=edid/1920x1080.bin"`
but when i use it in boot.ini from lakka it dont works.
Anyone can help?

**Comment by Kivutar** [comment]
I was able to reproduce this problem on one of my samsung TVs. This TV have a capacitor issue and 80% of the times, I will get a black screen with "No signal" message.

There are instructions on the web on how to fix it (unpluggin the screen during 15min, and more complex techniques). I doesn't always work.

Adding the setenv in the boot.ini fixed it for sometimes, then the problem came back.

**Comment by Rodrigomezs** [comment]
Adding the setenv works 100% times in Gamestation Turbo image. In Lakka doesnt works, 0%. it is frustrating, i have changed hdmi wire 100 times. I will use Gamestation for now, if you guys find a fix for this, answer here please.

**Comment by Kivutar** [comment]
Ok, I will upgrade the kernel and the blobs. It looks like I was still on memeka's branch.

**Comment by Rodrigomezs** [comment]
thanks for your effort.

**Comment by Kivutar** [comment]
It fixed the problem for me http://static.kivutar.me/Lakka-OdroidXU3.arm-devel-20160510210313-r21434-gd23434f.img.gz

**Comment by Rodrigomezs** [comment]
works!

**Comment by AndTheCookies** [comment]
I am so glad I kept this conversation bookmarked. @Kivutar the new link you posted works for me too!

**Comment by Kivutar** [comment]
Great :D

**Comment by Rodrigomezs** [comment]
I have this issue again on XU4 with hdmi and small screen monitors. I have the last build of lakka. in 32" screen with hdmi works fine.

**Comment by Kivutar** [comment]
http://odroid.com/dokuwiki/doku.php?id=supported_resolutions

**Comment by Rodrigomezs** [comment]
It should works
http://www.lg.com/uk/monitors/lg-22M47VQ
1920×1080

**Comment by Kivutar** [comment]
So maybe the screen is sending a wrong EDID? Can you try tweaking the boot.ini? Be carefull, the variable video_output have to be added in bootargs

**Comment by Rodrigomezs** [comment]
The problem was the HDMI wire, poor quality, thanks!
